export const GET_ALL_RECIPES = "GET_ALL_RECIPES";
export const GET_DETAILS = "GET_DETAILS";
export const SEARCH_BY_NAME = "SEARCH_BY_NAME";
export const ALPHABET_OR_RANK_ORDER = "ALPHABET_OR_RANK_ORDER";
export const GO_BACK_GET_DETAILS = "GO_BACK_GET_DETAILS";
export const POST_NEW_RECIPE = "POST_NEW_RECIPE";
export const GET_DIETS = "GET_DIETS";